"""Add image_url to attractions

Revision ID: 9b4d224e0bc3
Revises: 0d3affe3e0c1
Create Date: 2020-05-06 00:17:50.316753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4d224e0bc3'
down_revision = '0d3affe3e0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attractions', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attractions', 'image_url')
    # ### end Alembic commands ###
